# Generated by Django 5.1.1 on 2025-04-08 15:36

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Titel', models.CharField(max_length=100)),
                ('Images', models.FileField(upload_to='media/TraficImage/')),
                ('Body', tinymce.models.HTMLField()),
                ('PostDate', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Titel', models.CharField(max_length=100)),
                ('Images', models.FileField(upload_to='media/TraficImage/')),
                ('Body', tinymce.models.HTMLField()),
                ('PostDate', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/FeaturedImage/')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200)),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/GalleryImage/')),
            ],
        ),
        migrations.CreateModel(
            name='ProudlySponsoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.FileField(upload_to='media/TraficImage/')),
                ('Titel', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('ButtonLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/TraficImage/')),
            ],
        ),
    ]
