# Generated by Django 5.1.1 on 2025-04-08 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eventcategory_blog_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventcategory'),
        ),
    ]
