# Generated by Django 5.1.1 on 2025-04-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Thumbnail',
            field=models.FileField(default='', upload_to='media/Event/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='Images',
            field=models.FileField(upload_to='media/Blog/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Images',
            field=models.FileField(upload_to='media/Event/'),
        ),
    ]
