# Generated by Django 5.1.1 on 2025-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_event_thumbnail_alter_blog_images_alter_event_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='Location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
