# Generated by Django 5.1.1 on 2025-04-10 12:56

import datetime
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_event_author_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 10, 18, 56, 58, 805783)),
        ),
        migrations.AlterField(
            model_name='event',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 10, 18, 56, 58, 804795)),
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('JobType', models.CharField(max_length=100)),
                ('SalaryRange', models.CharField(max_length=100)),
                ('PostDate', models.DateField(default=datetime.datetime(2025, 4, 10, 18, 56, 58, 807829))),
                ('description', tinymce.models.HTMLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.careerscategory')),
            ],
        ),
    ]
