# Generated by Django 5.1.1 on 2025-04-10 13:14

import datetime
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_position_careers_vacancy_alter_blog_postdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 10, 19, 14, 39, 577799)),
        ),
        migrations.AlterField(
            model_name='event',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 10, 19, 14, 39, 577799)),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=100)),
                ('vacancy', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('JobType', models.CharField(max_length=100)),
                ('SalaryRange', models.CharField(max_length=100)),
                ('PostDate', models.DateField(default=datetime.datetime(2025, 4, 10, 19, 14, 39, 578921))),
                ('description', tinymce.models.HTMLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.careerscategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Careers',
        ),
    ]
