# Generated by Django 5.1.1 on 2025-04-16 17:08

import datetime
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_appliedcandidates_alter_blog_postdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms_Conditions', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Privacy_Policy', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='PublisherTermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms_Conditions', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 8, 37, 604837)),
        ),
        migrations.AlterField(
            model_name='career',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 8, 37, 605836)),
        ),
        migrations.AlterField(
            model_name='event',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 8, 37, 604837)),
        ),
    ]
