# Generated by Django 5.1.1 on 2025-04-16 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_advertisertermsandconditions_privacypolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisertermsandconditions',
            name='Last_Update',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 17, 57, 610727)),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='Last_Update',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 17, 57, 609730)),
        ),
        migrations.AddField(
            model_name='publishertermsandconditions',
            name='Last_Update',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 17, 57, 610727)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 17, 57, 608694)),
        ),
        migrations.AlterField(
            model_name='career',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 17, 57, 609730)),
        ),
        migrations.AlterField(
            model_name='event',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 23, 17, 57, 608479)),
        ),
    ]
