# Generated by Django 5.1.1 on 2025-07-08 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_advertisertermsandconditions_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisertermsandconditions',
            name='Last_Update',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 0, 22, 18, 69230)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 0, 22, 18, 69230)),
        ),
        migrations.AlterField(
            model_name='career',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 0, 22, 18, 69230)),
        ),
        migrations.AlterField(
            model_name='event',
            name='PostDate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='Last_Update',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 0, 22, 18, 69230)),
        ),
        migrations.AlterField(
            model_name='publishertermsandconditions',
            name='Last_Update',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 0, 22, 18, 69230)),
        ),
    ]
