# Generated by Django 5.1.1 on 2025-07-08 20:53

import datetime
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_advertisertermsandconditions_last_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms_Conditions', tinymce.models.HTMLField()),
                ('Last_Update', models.DateField(default=datetime.datetime(2025, 7, 9, 2, 53, 30, 810376))),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms_Conditions', tinymce.models.HTMLField()),
                ('Last_Update', models.DateField(default=datetime.datetime(2025, 7, 9, 2, 53, 30, 809362))),
            ],
        ),
        migrations.DeleteModel(
            name='AdvertiserTermsAndConditions',
        ),
        migrations.DeleteModel(
            name='PublisherTermsAndConditions',
        ),
        migrations.AlterField(
            model_name='blog',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 2, 53, 30, 807808)),
        ),
        migrations.AlterField(
            model_name='career',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 2, 53, 30, 807808)),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='Last_Update',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 2, 53, 30, 809362)),
        ),
    ]
